version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/HomePage-UI"
    schedule:
      interval: "daily"
      time: "11:00"
      timezone: "America/Toronto"
    commit-message:
      prefix: "deps(npm)"
    groups:
      ui-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "nuget"
    directory: "/HomePage-API"
    schedule:
      interval: "daily"
      time: "11:00"
      timezone: "America/Toronto"
    commit-message:
      prefix: "deps(nuget)"
    groups:
      api-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:00"
      timezone: "America/Toronto"
    commit-message:
      prefix: "deps(actions)"
