updates:
  - package-ecosystem: "npm"
    directory: "/HomePage-UI"
    schedule:
      interval: "daily"
      time: "13:50"
      timezone: "America/Toronto"
    commit-message:
      prefix: "deps(npm)"
    groups:
      frontend:
        patterns:
          - "*"

  - package-ecosystem: "nuget"
    directory: "/HomePage-API"
    schedule:
      interval: "daily"
      time: "13:50"
      timezone: "America/Toronto"
    commit-message:
      prefix: "deps(nuget)"
    groups:
      backend:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "13:50"
      timezone: "America/Toronto"
    commit-message:
      prefix: "deps(actions)"
