apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: homepage-test
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }

    http {
      server {
        listen 80;
        server_name romitsagu.com;
        return 301 https://$host$request_uri;
      }

      server {
        listen 443 ssl;
        server_name romitsagu.com;

        ssl_certificate /etc/ssl/certs/server.cert;
        ssl_certificate_key /etc/ssl/certs/server.key;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;
        ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";

        location / {
          proxy_pass http://localhost:3000;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection 'upgrade';
          proxy_set_header Host $host;
          proxy_cache_bypass $http_upgrade;
        }
      }
    }