name: Build API Docker CI

on:
  push:
    branches:
      - master
      - HomePage-V2-beta
    paths:
      - HomePage-API/**
  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
          with:
            driver: docker-container

        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            context: ./HomePage-API
            file: ./HomePage-API/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/homepage:api
        
        - name: Trigger Deploy Workflow
          uses: peter-evans/repository-dispatch@v3
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            event-type: build-completed