name: Build UI Docker CI

on:
  push:
    branches:
      - master
    paths:
      - HomePage-UI/**
  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v5

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
          with:
            driver: docker-container

        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            context: ./HomePage-UI
            file: ./HomePage-UI/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/homepage:ui
            build-args: |
              SYNCFUSION_LICENSE=${{ secrets.SyncfusionLicense }}
              NEXT_PUBLIC_UMAMI_WEBSITE_ID=${{ secrets.NEXT_PUBLIC_UMAMI_WEBSITE_ID }}
              NEXT_PUBLIC_UMAMI_URL=${{ secrets.NEXT_PUBLIC_UMAMI_URL }}
            # cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/homepage:ui-cache
            # cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/homepage:ui-cache,mode=max

        - name: Trigger Deploy Workflow
          uses: peter-evans/repository-dispatch@v4
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            event-type: build-completed