name: CI to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    env:
        KUBECONFIG: /root/.kube/config
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./HomePage/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/homepage:latest

      - name: Update Kubernetes Deployment
        run: |
          kubectl set image deployment/homepage homepage=${{ secrets.DOCKER_USERNAME }}/homepage:latest -n homepage
          kubectl annotate deployment homepage kubernetes.io/change-cause="Updated image to ${{ secrets.DOCKER_USERNAME }}/homepage:latest" --overwrite -n homepage
          kubectl rollout restart deployment/homepage -n homepage
